---
- name: Fail if this role does not support the distribution
  ansible.builtin.fail:
    msg: "Distribution {{ _docker_os_dist }} is not supported by this role!"
  vars:
    _supported_distributions:
      - AlmaLinux
      - CentOS
      - Debian
      - Fedora
      - RedHat
      - Ubuntu
      - Rocky
  when: _docker_os_dist not in _supported_distributions

- name: Fail if kernel version is lower than 3.10
  ansible.builtin.fail:
    msg: "Kernel version 3.10 or later is required!"
  when: ansible_kernel is version_compare("3.10", '<')

- name: Fail if unsupported version for distribution
  ansible.builtin.fail:
    msg: "{{ _docker_os_dist }} _version_checks[_docker_os_dist] or later is required!"
  vars:
    _version_checks:
      CentOS: 7
      Debian: 7
      Fedora: 24
      RedHat: 7
      Ubuntu: 14
  when:
    - _docker_os_dist in _version_checks
    - _docker_os_dist_major_version | int < _version_checks[_docker_os_dist]
