apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: haproxy-controller
spec:
  isCA: true
  commonName: rootCA
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: intermediate-issuer
  namespace: haproxy-controller
spec:
  ca:
    secretName: root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca
  namespace: haproxy-controller
spec:
  isCA: true
  commonName: IntermediateCA
  secretName: intermediate-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: intermediate-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer
  namespace: haproxy-controller
spec:
  ca:
    secretName: intermediate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ha-cert
  namespace: haproxy-controller
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: "91.206.15.220"
  ipAddresses:
  - 91.206.15.220
  dnsNames:
    - "91.206.15.220"
  secretName: ha-cert-tls
  issuerRef:
    name: cert-issuer