# Copyright 2019 HAProxy Technologies LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Default values for kubernetes-ingress Chart for HAProxy Ingress Controller
## ref: https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation


## Controller default values
controller:
  kind: Deployment    # can be 'Deployment' or 'DaemonSet'
  ingressClass: null
  replicaCount: 1

  stats:
    enabled: true
  metrics:
    enabled: true

  ## Controller Service configuration
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    enabled: true     # set to false when controller.kind is 'DaemonSet' and controller.daemonset.useHostPorts is true

    ## Service nodePorts to use for http, https and stat
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/
    ## If empty, random ports will be used
    nodePorts:
      http: 31080
      https: 31443
      stat: 31024

  ## ServiceMonitor
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md
  ## Note: requires Prometheus Operator to be able to work, for example:
  ## helm install prometheus prometheus-community/kube-prometheus-stack \
  ##   --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
  ##   --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false
  serviceMonitor:
    ## Toggle the ServiceMonitor true if you have Prometheus Operator installed and configured
    enabled: true

    ## Specify the endpoints
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/design.md#servicemonitor
    endpoints:
      - port: stat
        path: /metrics
        scheme: http
        interval: 30s

