groups:
  - name: rate-alerting
    rules:
      - alert: HighLogRate
        expr: |
          sum by (container)
            (rate({level="error"}[1m]))
            > 30
        for: 1m
        labels:
            severity: warning
            team: devops
            category: logs
        annotations:
            title: "High LogRate Alert"
            description: "Something is logging a lot"
            impact: "impact"
            action: "action"
            dashboard: "https://grafana.com/service-dashboard"
            runbook: "https://wiki.com"
            logurl: "https://grafana.com/log-explorer"