server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://haproxy:3100/loki/api/v1/push
    tenant_id: docker

scrape_configs:
- job_name: docker # unix /var/run/docker.sock: connect: permission denied
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      refresh_interval: "5s"
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        timestamp: time
  - regex:
      expression: '(level|lvl|severity)=(?P<level>\w+)'
  - labels:
      stream:
      level:
  - timestamp:
      source: timestamp
      format: RFC3339Nano
  - output:
      source: output

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/*/containers/*/*log
  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - output:
      source: output


- job_name: journal
  journal:
    # read entries no older than 6h
    max_age: 6h
    path: /var/log/journal
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'