server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://haproxy:3100/loki/api/v1/push
    tenant_id: docker

scrape_configs:
- job_name: kafka
  kafka:
    brokers:
    - kafka1:9092
    - kafka2:9092
    - kafka3:9092
    topics:
    - ^[^_].*
    labels:
      job: kafka-logs
  relabel_configs:
      - action: replace
        source_labels:
          - __meta_kafka_topic
        target_label: topic
      - action: replace
        source_labels:
          - __meta_kafka_partition
        target_label: partition
      - action: replace
        source_labels:
          - __meta_kafka_group_id
        target_label: group
      - action: replace
        source_labels:
          - __meta_kafka_message_key
        target_label: message_key