FROM node:16-alpine
WORKDIR /app
COPY package.json yarn.lock nest-cli.json ./
RUN yarn install --production=true --frozen-lockfile && \
    yarn cache clean && \
    yarn global add @nestjs/cli
COPY tsconfig.json tsconfig.build.json ./
COPY src ./src
ADD https://raw.githubusercontent.com/epershinaass/exchange_typescript/main/balance/src/proto/balance.proto ./src/balance/proto/balance.proto
ADD https://raw.githubusercontent.com/epershinaass/exchange_typescript/main/products/src/proto/products.proto ./src/products/proto/products.proto
RUN yarn build

CMD [ "yarn", "start:dev" ]
