{
 "title": "HAProxy",
 "description": "Prometheus HAProxy dashboard",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-30h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_up, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(haproxy_up, instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{instance=~\"$host:$port\"}, backend)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{instance=~\"$host:$port\"}, frontend)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_bytes_in_total{instance=~\"$host:$port\", backend=~\"$backend\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=~\"$host:$port\", backend=~\"$backend\", server=~\"$server\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Basic Backend status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backends Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(haproxy_backend_up{backend=~\"$backend\", instance=~\"$host:$port\"} == 1)",
     "legendFormat": "Backends Up"
    },
    {
     "expr": "count(haproxy_backend_up{backend=~\"$backend\",instance=~\"$host:$port\"} == 0)",
     "legendFormat": "Backends Down"
    }
   ]
  },
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",instance=~\"$host:$port\"}[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",instance=~\"$host:$port\"}[5m])) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(irate(haproxy_backend_bytes_in_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(irate(haproxy_backend_bytes_out_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_connections_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(irate(haproxy_backend_connections_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Back"
    },
    {
     "expr": "sum(irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "Total requests / responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(irate(haproxy_backend_response_errors_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Response errors"
    },
    {
     "expr": "sum(irate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Requests errors"
    },
    {
     "expr": "sum(irate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Backend redispatch"
    },
    {
     "expr": "sum(irate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Backend retry"
    },
    {
     "expr": "sum(irate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Request denied"
    },
    {
     "expr": "sum(haproxy_backend_current_queue{backend=~\"$backend\",instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "Backend Queued"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "Frontend current sessions"
    },
    {
     "expr": "sum(haproxy_frontend_current_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "Frontend current session rate"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "Backend current sessions"
    },
    {
     "expr": "sum(haproxy_backend_current_session_rate{backend=~\"$backend\",instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "Backend current session rate"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "IN-{{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_bytes_out_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "OUT-{{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "IN-{{ frontend }}"
    },
    {
     "expr": "irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "OUT-{{ frontend }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Total number of connections OK / Error",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connections_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} Error"
    }
   ]
  },
  {
   "title": "Front - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_connections_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Maximum observed number of queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_max_queue{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Back - Current number of queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Total of redispatch / error / retry warnings",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Redispatch {{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_retry_warnings_total{backend=~\"$backend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Retry {{ backend }}"
    },
    {
     "expr": "irate(haproxy_backend_response_errors_total{backend=~\"$backend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Error {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Total HTTP requests OK / Error / Denied",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ frontend }}"
    },
    {
     "expr": "irate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ frontend }} Error"
    },
    {
     "expr": "irate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ frontend }} Denied"
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ code }} {{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\", code=~\"$code\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ code }} {{ frontend }} "
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_session_rate{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Back - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    },
    {
     "expr": "haproxy_backend_limit_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} limit"
    }
   ]
  },
  {
   "title": "Front - Maximum observed number of active sessions and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ frontend }}"
    },
    {
     "expr": "haproxy_frontend_limit_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ frontend }} limit"
    }
   ]
  },
  {
   "title": "Back - Maximum number of sessions rate per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Front - Maximum number of sessions rate per second and limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ frontend }}"
    },
    {
     "expr": "haproxy_frontend_limit_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ frontend }} limit"
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Current health status of the backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_up{backend=~\"$backend\", instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Back - Total weight of the servers in the backend / Active servers backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_weight{backend=~\"$backend\", instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "By Server Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "IN-{{ backend }} / {{ server }}"
    },
    {
     "expr": "irate(haproxy_server_bytes_out_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "OUT-{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connections_total{backend=~\"$backend\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Maximum observed number of queued requests assigned to this server",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_max_queue{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of queued requests assigned to this server",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_current_queue{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total of HTTP responses OK",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])) by (server)",
     "legendFormat": "{{ backend }} {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total of retry / error / redispatch warnings",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_retry_warnings_total{backend=~\"$backend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Retry {{ backend }} {{ server }}"
    },
    {
     "expr": "haproxy_server_redispatch_warnings_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "Redispatch {{ backend }} {{ server }}"
    },
    {
     "expr": "irate(haproxy_server_response_errors_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Error {{ backend }} {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} {{ server }} {{ code }}"
    }
   ]
  },
  {
   "title": "By Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Maximum observed number of sessions rate per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Maximum observed number of active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Health Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 235 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total downtime in seconds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 236 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_downtime_seconds_total{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total number of failed health checks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 236 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_check_failures_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total of connection errors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_errors_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Previously run health check duration, in milliseconds",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 249 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_seconds{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current health status of the server",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 262 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current weight of the server",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 262 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Scrape info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of errors while parsing CSV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_exporter_csv_parse_failures_total{instance=~\"$host:$port\"}",
     "legendFormat": "Exporter csv failures"
    }
   ]
  },
  {
   "title": "Current total HAProxy scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_exporter_scrapes_total{instance=~\"$host:$port\"}",
     "legendFormat": "HAProxy scrapes"
    }
   ]
  }
 ]
}