---
- name: Reset fact related to removal of old Docker
  ansible.builtin.set_fact:
    _remove_old_docker: false

- name: Determine Docker version
  ansible.builtin.shell: "docker version --format='{{ '{{' }} .Client.Version {{ '}}' }}' 2>/dev/null"
  register: _cmd_docker_version
  changed_when: false
  failed_when: false
  check_mode: no

- name: Set fact if old Docker installation shall be removed
  ansible.builtin.set_fact:
    _remove_old_docker: true
  when:
    - _cmd_docker_version.stdout_lines is defined
    - _cmd_docker_version.stdout_lines[0] is defined
    - _cmd_docker_version.stdout_lines[0] | int is version(17, '<')

- name: Check if Docker is running
  become: true
  ansible.builtin.systemd:
    name: docker
  ignore_errors: yes
  register: _service_docker_status
  check_mode: no
  when: _remove_old_docker | bool

- name: Stop Docker service
  ansible.builtin.service:
    use: "{{ docker_x_service_mgr }}"
    name: docker
    state: stopped
  when: "_service_docker_status.rc | default(1) == 0"

- name: Remove old Docker installation before Docker CE
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  register: _pkg_result
  until: _pkg_result is succeeded
  when: _remove_old_docker | bool
  loop: "{{ docker_old_packages[_docker_os_dist] | default(docker_old_packages[_docker_os_dist_file_varity]) }}"
