apiVersion: v1
kind: Secret
metadata:
    name: jfrogregistrykey
    namespace: application
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MGPZ87CMSR9iqfWhJqiwnceO86fJQ0LA268uDobqjz5AwoqYb5wDeUssr8makbF3h2lXHXjBMXRj1z1kEJF5tKio+8Zlz5CrC5eDXgNHXFqYBVxFzpHII7WhFDYyxWxS2+ezz5CXtisk66EfF5uR3mSpebyi8HFZOYyZFIQmQdlRb+xJwYaPos2HhDvIRQtOVv3Mdg==,iv:XBRI++4QvQreEt0hX6IFzCxHTLQqTHgIGXgyrIsXpIg=,tag:DpFlu9DnMuLSBb9TebSBtA==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:44:14Z"
    mac: ENC[AES256_GCM,data:w/OoBRfWw2/3466V+2rpL4AZ/8fkAZZsAkgeXx3pOxtjXdMnSn9uQmU4H2AHaAKjzt4ckXf1K3q/43kuRjF8LMKBdAsWdDd556wIb7Hb6Jkz1PjW7S+mgQiOkFo5d9GYj7KD/MUsYA6u6Vbh6P+h9HQ3ekGq/5jeAHSZcn6GeHo=,iv:at+jTn3NM3JBTkESyX1juNCOwDUOzaSzgxjuaZpBDNo=,tag:Fn3hkMj8Pj/51hsjuU8UEQ==,type:str]
    pgp:
        - created_at: "2022-08-25T09:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA91z77s82I0xAQ//aLwfU77em1YULc42EKwKddkLskRFhYjy1OGqSbe4OmPM
            j6DhwYirMmaYwHuyplQkXAtH3hI3BQ0x580ZvRMCNuBrR4n5Nwn3gLFTFwOgNiws
            lyFa5TFi8F3mSUTYVDFEaprp0NYbklbdP3yVySa6N4MRkEipZNMapEFcTWlLqLjB
            4/uavElwPw2+yWhBX6zV9z05p6m+KeqE+eeFahipJYC+sHlyKUTflIfspIw1UlxE
            jLjhLtIUmezxqFK6X8OHhbVk3z3oGfRzuIo/1qi/FrnKi9epCS/VUVufz6XdafAH
            PzRa2UEPONgauTJ4c7h4m7Pjrv8JHZssscTqrFOran/xS4PG3XTPxvajNWtvkk/s
            S3haEkq5g8Uqs/5ftMox0ZU0KgcmNN50/16xrvQ0SAWydOzwAxcIJiWzroxA6xk0
            3tbR+jiDiyFKgp7y+EPRNx45deA5fpsnXBtMN0ueaoi300TPH53KpQzprfmsiKFm
            9ijR9zLr9uIVheglXDTnRAJzxJwRqpWJbDHroELH3GRJcKv77wJpYeiHqoiROvT5
            DgsellnmNJ0nz3iyIeWsOyVn4OZYC55Y6g+UOwTlQqzItV/OXpbdU1r5j66s3MDV
            07M5Hupl2GQYiqf/BML7GwsbOf3J+fX+VC7/4sFnR1ttAHd1c/xKtU1WmXiL9RvS
            XgE0mNzNlnQhHWJOW3cK6xLpc94NMiMBeKo65K7VwhRzCkpvMqC7hfBi+f/6oIxE
            /o92k/P+jmHk8NqfPS0yJqZjbpZuCgwbUFLdnU5E/kvFbtcsCZdhtYT5EDe9XKQ=
            =eVkT
            -----END PGP MESSAGE-----
          fp: 6823909579D1906E4C6B63093B78EBE6A6AA3A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: account-env
    namespace: application
type: Opaque
stringData:
    .env: ENC[AES256_GCM,data:Tk7nQvSgmjXss6QWFOtvJ4ilbv4kxRXunwKlB76if3atcfYQyYWLx9quhOfxdLXIPeUbcgbXOtbg9PykpqCQK08vAw8KEHzO2I7AMiMGMK0DfxGUN2FidkGPS3afsRfd996UuUHyqKi8GfO7QxKczmBF8+t9TgGnfl9e8sihcpzgUGpJMVG90uLjgaHVu72LSxduN9I6CSfj9JJwBtapvlSQFcP9BZ5BrnOQxr1nQHYvduC2NhhV/Bki0fLY0TUSxuDVj+MkXUi6cYU4Q+I/LqlTNSCGa/2Dq1s5f5ner8STTiZzIepP2G3agR8pgl2Me7b6g9GFOZcXath8lA7SVo/8SeBe,iv:Lqy1ZU0CdOd/T1e1MAzr/NjBi2EXElejgtaRicSINxU=,tag:Hb8banaFIJPB92ScVSz8GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:44:14Z"
    mac: ENC[AES256_GCM,data:w/OoBRfWw2/3466V+2rpL4AZ/8fkAZZsAkgeXx3pOxtjXdMnSn9uQmU4H2AHaAKjzt4ckXf1K3q/43kuRjF8LMKBdAsWdDd556wIb7Hb6Jkz1PjW7S+mgQiOkFo5d9GYj7KD/MUsYA6u6Vbh6P+h9HQ3ekGq/5jeAHSZcn6GeHo=,iv:at+jTn3NM3JBTkESyX1juNCOwDUOzaSzgxjuaZpBDNo=,tag:Fn3hkMj8Pj/51hsjuU8UEQ==,type:str]
    pgp:
        - created_at: "2022-08-25T09:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA91z77s82I0xAQ//aLwfU77em1YULc42EKwKddkLskRFhYjy1OGqSbe4OmPM
            j6DhwYirMmaYwHuyplQkXAtH3hI3BQ0x580ZvRMCNuBrR4n5Nwn3gLFTFwOgNiws
            lyFa5TFi8F3mSUTYVDFEaprp0NYbklbdP3yVySa6N4MRkEipZNMapEFcTWlLqLjB
            4/uavElwPw2+yWhBX6zV9z05p6m+KeqE+eeFahipJYC+sHlyKUTflIfspIw1UlxE
            jLjhLtIUmezxqFK6X8OHhbVk3z3oGfRzuIo/1qi/FrnKi9epCS/VUVufz6XdafAH
            PzRa2UEPONgauTJ4c7h4m7Pjrv8JHZssscTqrFOran/xS4PG3XTPxvajNWtvkk/s
            S3haEkq5g8Uqs/5ftMox0ZU0KgcmNN50/16xrvQ0SAWydOzwAxcIJiWzroxA6xk0
            3tbR+jiDiyFKgp7y+EPRNx45deA5fpsnXBtMN0ueaoi300TPH53KpQzprfmsiKFm
            9ijR9zLr9uIVheglXDTnRAJzxJwRqpWJbDHroELH3GRJcKv77wJpYeiHqoiROvT5
            DgsellnmNJ0nz3iyIeWsOyVn4OZYC55Y6g+UOwTlQqzItV/OXpbdU1r5j66s3MDV
            07M5Hupl2GQYiqf/BML7GwsbOf3J+fX+VC7/4sFnR1ttAHd1c/xKtU1WmXiL9RvS
            XgE0mNzNlnQhHWJOW3cK6xLpc94NMiMBeKo65K7VwhRzCkpvMqC7hfBi+f/6oIxE
            /o92k/P+jmHk8NqfPS0yJqZjbpZuCgwbUFLdnU5E/kvFbtcsCZdhtYT5EDe9XKQ=
            =eVkT
            -----END PGP MESSAGE-----
          fp: 6823909579D1906E4C6B63093B78EBE6A6AA3A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: facade-env
    namespace: application
type: Opaque
stringData:
    .env: ENC[AES256_GCM,data:vWXcWIb1RULkEVnQCKUw6Jlx1e/sQNop1hwc4aCkzGyLr2XjEwGxbD9aqGCe/HbZNDFAFwf3U972nYKsJVzFPylDXtEve3Euz4oLORnn/3H92B/tD87F96yyPLfB/rEkFcGXxIeTQ8W2GAUUeDwVY+UlGPQ1pi4QIYj00OmUbvtMHvAqQoVoyJh+DXmG6mPplUo2sNIvNP+LuA==,iv:Idvpds0ToZyTyxcic5TN1/4MCtOus8QJhXSjPuhP5WU=,tag:tV7ob6zFZfjaujOXNVcpeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:44:14Z"
    mac: ENC[AES256_GCM,data:w/OoBRfWw2/3466V+2rpL4AZ/8fkAZZsAkgeXx3pOxtjXdMnSn9uQmU4H2AHaAKjzt4ckXf1K3q/43kuRjF8LMKBdAsWdDd556wIb7Hb6Jkz1PjW7S+mgQiOkFo5d9GYj7KD/MUsYA6u6Vbh6P+h9HQ3ekGq/5jeAHSZcn6GeHo=,iv:at+jTn3NM3JBTkESyX1juNCOwDUOzaSzgxjuaZpBDNo=,tag:Fn3hkMj8Pj/51hsjuU8UEQ==,type:str]
    pgp:
        - created_at: "2022-08-25T09:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA91z77s82I0xAQ//aLwfU77em1YULc42EKwKddkLskRFhYjy1OGqSbe4OmPM
            j6DhwYirMmaYwHuyplQkXAtH3hI3BQ0x580ZvRMCNuBrR4n5Nwn3gLFTFwOgNiws
            lyFa5TFi8F3mSUTYVDFEaprp0NYbklbdP3yVySa6N4MRkEipZNMapEFcTWlLqLjB
            4/uavElwPw2+yWhBX6zV9z05p6m+KeqE+eeFahipJYC+sHlyKUTflIfspIw1UlxE
            jLjhLtIUmezxqFK6X8OHhbVk3z3oGfRzuIo/1qi/FrnKi9epCS/VUVufz6XdafAH
            PzRa2UEPONgauTJ4c7h4m7Pjrv8JHZssscTqrFOran/xS4PG3XTPxvajNWtvkk/s
            S3haEkq5g8Uqs/5ftMox0ZU0KgcmNN50/16xrvQ0SAWydOzwAxcIJiWzroxA6xk0
            3tbR+jiDiyFKgp7y+EPRNx45deA5fpsnXBtMN0ueaoi300TPH53KpQzprfmsiKFm
            9ijR9zLr9uIVheglXDTnRAJzxJwRqpWJbDHroELH3GRJcKv77wJpYeiHqoiROvT5
            DgsellnmNJ0nz3iyIeWsOyVn4OZYC55Y6g+UOwTlQqzItV/OXpbdU1r5j66s3MDV
            07M5Hupl2GQYiqf/BML7GwsbOf3J+fX+VC7/4sFnR1ttAHd1c/xKtU1WmXiL9RvS
            XgE0mNzNlnQhHWJOW3cK6xLpc94NMiMBeKo65K7VwhRzCkpvMqC7hfBi+f/6oIxE
            /o92k/P+jmHk8NqfPS0yJqZjbpZuCgwbUFLdnU5E/kvFbtcsCZdhtYT5EDe9XKQ=
            =eVkT
            -----END PGP MESSAGE-----
          fp: 6823909579D1906E4C6B63093B78EBE6A6AA3A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: balance-env
    namespace: application
type: Opaque
stringData:
    .env: ENC[AES256_GCM,data:mOhjrt4pb0oXr+8NzhOVCn2vAdexGv3Wuz4Hhp7i0R5ZopzdYtTFA3eL7FNsQ6HbvX3Hvit70oHICjn1U5RM8g+ENPKRizg3QZm+1++JWzUpX2/EgVAA/6yqTxIdXOxy5JOLcONv4JGbD5uIOy0Q3E6BODPbroa2UCR1tquS++99GLBW5yD94rjOnYVOiOwvcnwoq/0JfIRsx0w/WlyEpbLXqSk=,iv:s8A4FHh6X09r5eZM7WrgBH/Xco9XBPAMDCMy3nnrx30=,tag:1VHT82HPNrXlNnwLOe+oCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:44:14Z"
    mac: ENC[AES256_GCM,data:w/OoBRfWw2/3466V+2rpL4AZ/8fkAZZsAkgeXx3pOxtjXdMnSn9uQmU4H2AHaAKjzt4ckXf1K3q/43kuRjF8LMKBdAsWdDd556wIb7Hb6Jkz1PjW7S+mgQiOkFo5d9GYj7KD/MUsYA6u6Vbh6P+h9HQ3ekGq/5jeAHSZcn6GeHo=,iv:at+jTn3NM3JBTkESyX1juNCOwDUOzaSzgxjuaZpBDNo=,tag:Fn3hkMj8Pj/51hsjuU8UEQ==,type:str]
    pgp:
        - created_at: "2022-08-25T09:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA91z77s82I0xAQ//aLwfU77em1YULc42EKwKddkLskRFhYjy1OGqSbe4OmPM
            j6DhwYirMmaYwHuyplQkXAtH3hI3BQ0x580ZvRMCNuBrR4n5Nwn3gLFTFwOgNiws
            lyFa5TFi8F3mSUTYVDFEaprp0NYbklbdP3yVySa6N4MRkEipZNMapEFcTWlLqLjB
            4/uavElwPw2+yWhBX6zV9z05p6m+KeqE+eeFahipJYC+sHlyKUTflIfspIw1UlxE
            jLjhLtIUmezxqFK6X8OHhbVk3z3oGfRzuIo/1qi/FrnKi9epCS/VUVufz6XdafAH
            PzRa2UEPONgauTJ4c7h4m7Pjrv8JHZssscTqrFOran/xS4PG3XTPxvajNWtvkk/s
            S3haEkq5g8Uqs/5ftMox0ZU0KgcmNN50/16xrvQ0SAWydOzwAxcIJiWzroxA6xk0
            3tbR+jiDiyFKgp7y+EPRNx45deA5fpsnXBtMN0ueaoi300TPH53KpQzprfmsiKFm
            9ijR9zLr9uIVheglXDTnRAJzxJwRqpWJbDHroELH3GRJcKv77wJpYeiHqoiROvT5
            DgsellnmNJ0nz3iyIeWsOyVn4OZYC55Y6g+UOwTlQqzItV/OXpbdU1r5j66s3MDV
            07M5Hupl2GQYiqf/BML7GwsbOf3J+fX+VC7/4sFnR1ttAHd1c/xKtU1WmXiL9RvS
            XgE0mNzNlnQhHWJOW3cK6xLpc94NMiMBeKo65K7VwhRzCkpvMqC7hfBi+f/6oIxE
            /o92k/P+jmHk8NqfPS0yJqZjbpZuCgwbUFLdnU5E/kvFbtcsCZdhtYT5EDe9XKQ=
            =eVkT
            -----END PGP MESSAGE-----
          fp: 6823909579D1906E4C6B63093B78EBE6A6AA3A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: products-env
    namespace: application
type: Opaque
stringData:
    .env: ENC[AES256_GCM,data:cd8gE71tl27LSa66BbhwODGwgAiCIRLc4HWG6xOv2NmA5tVOoZbNhMIOyZGk02z+AchESXDWiREtItqbExsJFuZWDugdSGDWxt0frAUJq2CuT5BOMSA0qz5GaZqIoBSkN5D0aSRwv5CA6SALu2ezcXoIbYkPNL+SNSEoe4Mpm4KyjWFUMOzHWjIWYZT/dyYQuWaxJtCqVsmpGi32eA5IfiQQLfrM,iv:8JTMor4tDONZiR1YGd3dxF1cqHiPuEPnoEAycsZdHGI=,tag:+4laE1CLjHic/DK/2FRAGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:44:14Z"
    mac: ENC[AES256_GCM,data:w/OoBRfWw2/3466V+2rpL4AZ/8fkAZZsAkgeXx3pOxtjXdMnSn9uQmU4H2AHaAKjzt4ckXf1K3q/43kuRjF8LMKBdAsWdDd556wIb7Hb6Jkz1PjW7S+mgQiOkFo5d9GYj7KD/MUsYA6u6Vbh6P+h9HQ3ekGq/5jeAHSZcn6GeHo=,iv:at+jTn3NM3JBTkESyX1juNCOwDUOzaSzgxjuaZpBDNo=,tag:Fn3hkMj8Pj/51hsjuU8UEQ==,type:str]
    pgp:
        - created_at: "2022-08-25T09:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA91z77s82I0xAQ//aLwfU77em1YULc42EKwKddkLskRFhYjy1OGqSbe4OmPM
            j6DhwYirMmaYwHuyplQkXAtH3hI3BQ0x580ZvRMCNuBrR4n5Nwn3gLFTFwOgNiws
            lyFa5TFi8F3mSUTYVDFEaprp0NYbklbdP3yVySa6N4MRkEipZNMapEFcTWlLqLjB
            4/uavElwPw2+yWhBX6zV9z05p6m+KeqE+eeFahipJYC+sHlyKUTflIfspIw1UlxE
            jLjhLtIUmezxqFK6X8OHhbVk3z3oGfRzuIo/1qi/FrnKi9epCS/VUVufz6XdafAH
            PzRa2UEPONgauTJ4c7h4m7Pjrv8JHZssscTqrFOran/xS4PG3XTPxvajNWtvkk/s
            S3haEkq5g8Uqs/5ftMox0ZU0KgcmNN50/16xrvQ0SAWydOzwAxcIJiWzroxA6xk0
            3tbR+jiDiyFKgp7y+EPRNx45deA5fpsnXBtMN0ueaoi300TPH53KpQzprfmsiKFm
            9ijR9zLr9uIVheglXDTnRAJzxJwRqpWJbDHroELH3GRJcKv77wJpYeiHqoiROvT5
            DgsellnmNJ0nz3iyIeWsOyVn4OZYC55Y6g+UOwTlQqzItV/OXpbdU1r5j66s3MDV
            07M5Hupl2GQYiqf/BML7GwsbOf3J+fX+VC7/4sFnR1ttAHd1c/xKtU1WmXiL9RvS
            XgE0mNzNlnQhHWJOW3cK6xLpc94NMiMBeKo65K7VwhRzCkpvMqC7hfBi+f/6oIxE
            /o92k/P+jmHk8NqfPS0yJqZjbpZuCgwbUFLdnU5E/kvFbtcsCZdhtYT5EDe9XKQ=
            =eVkT
            -----END PGP MESSAGE-----
          fp: 6823909579D1906E4C6B63093B78EBE6A6AA3A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: order-env
    namespace: application
type: Opaque
stringData:
    .env: ENC[AES256_GCM,data:Qzf4koQ723vDUQtRE6I717DDLZM6F5+/RGfHWb+/ro5FNJ4Hz7e9jdDugvbrIyB15tF8p/g6F+Gii8QSS7I121fdzGLrdnC4hIXsQCDJY4NUkb31IXREK1wU2Hbq2vwbt6s36RSePRECPP3gPOU09NtwUmOX9Ddq8sLu2Gk3QeVgOPT6kKW1+WuYeJyXFoCXVBog4PvBwTqHGTDlijcOoSdRWseNUTcMPIwdv3gkVLhhPv9ywepy8tOlQ/qHCSQFl0c88Z6rzb0ugc9DvzSD1pf/8xFCCq2LSg==,iv:HTb5MjOQNo+HhWM0dtZOe4BkZGGMNjZS0JnykzZjRdQ=,tag:KMqaom73v17z60HDc62rOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:44:14Z"
    mac: ENC[AES256_GCM,data:w/OoBRfWw2/3466V+2rpL4AZ/8fkAZZsAkgeXx3pOxtjXdMnSn9uQmU4H2AHaAKjzt4ckXf1K3q/43kuRjF8LMKBdAsWdDd556wIb7Hb6Jkz1PjW7S+mgQiOkFo5d9GYj7KD/MUsYA6u6Vbh6P+h9HQ3ekGq/5jeAHSZcn6GeHo=,iv:at+jTn3NM3JBTkESyX1juNCOwDUOzaSzgxjuaZpBDNo=,tag:Fn3hkMj8Pj/51hsjuU8UEQ==,type:str]
    pgp:
        - created_at: "2022-08-25T09:44:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA91z77s82I0xAQ//aLwfU77em1YULc42EKwKddkLskRFhYjy1OGqSbe4OmPM
            j6DhwYirMmaYwHuyplQkXAtH3hI3BQ0x580ZvRMCNuBrR4n5Nwn3gLFTFwOgNiws
            lyFa5TFi8F3mSUTYVDFEaprp0NYbklbdP3yVySa6N4MRkEipZNMapEFcTWlLqLjB
            4/uavElwPw2+yWhBX6zV9z05p6m+KeqE+eeFahipJYC+sHlyKUTflIfspIw1UlxE
            jLjhLtIUmezxqFK6X8OHhbVk3z3oGfRzuIo/1qi/FrnKi9epCS/VUVufz6XdafAH
            PzRa2UEPONgauTJ4c7h4m7Pjrv8JHZssscTqrFOran/xS4PG3XTPxvajNWtvkk/s
            S3haEkq5g8Uqs/5ftMox0ZU0KgcmNN50/16xrvQ0SAWydOzwAxcIJiWzroxA6xk0
            3tbR+jiDiyFKgp7y+EPRNx45deA5fpsnXBtMN0ueaoi300TPH53KpQzprfmsiKFm
            9ijR9zLr9uIVheglXDTnRAJzxJwRqpWJbDHroELH3GRJcKv77wJpYeiHqoiROvT5
            DgsellnmNJ0nz3iyIeWsOyVn4OZYC55Y6g+UOwTlQqzItV/OXpbdU1r5j66s3MDV
            07M5Hupl2GQYiqf/BML7GwsbOf3J+fX+VC7/4sFnR1ttAHd1c/xKtU1WmXiL9RvS
            XgE0mNzNlnQhHWJOW3cK6xLpc94NMiMBeKo65K7VwhRzCkpvMqC7hfBi+f/6oIxE
            /o92k/P+jmHk8NqfPS0yJqZjbpZuCgwbUFLdnU5E/kvFbtcsCZdhtYT5EDe9XKQ=
            =eVkT
            -----END PGP MESSAGE-----
          fp: 6823909579D1906E4C6B63093B78EBE6A6AA3A79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
