{
 "title": "Kafka",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [
  "JVM",
  "Kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "release", "label": "release", "query": { "query": "label_values(release)" } }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=~\"kafka.\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=~\"kafka.\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{job=~\"kafka.\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=~\"kafka.\"}",
     "legendFormat": "Used {{job}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\", job=~\"kafka.\"}",
     "legendFormat": "Max {{job}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=~\"kafka.\"}",
     "legendFormat": "Used  {{job}}"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"kafka.\", pool=\"G1 Eden Space\"}",
     "legendFormat": "Max  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"kafka.\", pool=\"G1 Eden Space\"}",
     "legendFormat": "Used  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"kafka.\", pool=\"G1 Eden Space\"}",
     "legendFormat": "Committed  {{job}}"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"kafka.\", pool=\"G1 Old Gen\"}",
     "legendFormat": "Max  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"kafka.\", pool=\"G1 Old Gen\"}",
     "legendFormat": "Used  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"kafka.\", pool=\"G1 Old Gen\"}",
     "legendFormat": "Committed  {{job}}"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"kafka.\", pool=\"G1 Survivor Space\"}",
     "legendFormat": "Max  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"kafka.\", pool=\"G1 Survivor Space\"}",
     "legendFormat": "Used  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"kafka.\", pool=\"G1 Survivor Space\"}",
     "legendFormat": "Committed  {{job}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"kafka.\", pool=\"Metaspace\"}",
     "legendFormat": "Max {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"kafka.\", pool=\"Metaspace\"}",
     "legendFormat": "Used {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"kafka.\", pool=\"Metaspace\"}",
     "legendFormat": "Committed {{job}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"kafka.\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Max {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"kafka.\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Used {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"kafka.\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed {{job}}"
    }
   ]
  },
  {
   "title": "Code Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"kafka.\", pool=~\"CodeHeap .*\"}",
     "legendFormat": "Max {{job}} {{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"kafka.\", pool=~\"CodeHeap .*\"}",
     "legendFormat": "Used {{job}} {{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"kafka.\", pool=~\"CodeHeap .*\"}",
     "legendFormat": "Committed {{job}} {{pool}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"kafka.\"}",
     "legendFormat": "JVM current threads  {{job}}"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"kafka.\"}",
     "legendFormat": "JVM daemon threads {{job}}"
    },
    {
     "expr": "jvm_threads_deadlocked{job=~\"kafka.\"}",
     "legendFormat": "JVM deadlocked threads  {{job}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"kafka.\"}",
     "legendFormat": "{{gc}}  {{job}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"kafka.\"}[5m])",
     "legendFormat": "{{gc}} {{job}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{job=~\"kafka.\"}",
     "legendFormat": "loaded  {{job}}"
    }
   ]
  }
 ]
}