apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: devops-rbac
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
  - kind: Group
    name: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: rolebinding:view
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
  - kind: Group
    name: view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: mongodb-operator
    name: role:mongo-forward
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
    verbs:
      - "get"
      - "create"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "services"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: mongodb-operator
  name: rolebinding:mongo-forward
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role:mongo-forward
subjects:
- kind: Group
  name: mongo-forward
  namespace: mongodb-operator