# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['prometheus:9090']
    basic_auth:
      username: prometheus
      password: ${PROMETHEUS_DATASOURCE_PASSWORD}

  - job_name: cadvisor
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: grafana
    static_configs:
    - targets: ['grafana:3000']

  - job_name: node-exporter
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'kafka-exporter'
    static_configs:
    - targets: ['kafka-exporter:9308']

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'haproxy'
    static_configs:
    - targets: ['haproxy-exporter:9101']

  - job_name: 'kafka1'
    static_configs:
    - targets: ['kafka1:9101']

  - job_name: 'kafka2'
    static_configs:
    - targets: ['kafka2:9101']

  - job_name: 'kafka3'
    static_configs:
    - targets: ['kafka3:9101']

  - job_name: 'schema-registry'
    static_configs:
    - targets: ['schema-registry:9101']

  - job_name: 'mongodb-balance'
    static_configs:
    - targets: ['mongodb-balance:9216']

  - job_name: 'mongodb-products'
    static_configs:
    - targets: ['mongodb-products:9216']

  - job_name: 'mongodb-account'
    static_configs:
    - targets: ['mongodb-account:9216']

  - job_name: 'mongodb-order'
    static_configs:
    - targets: ['mongodb-order:9216']

  - job_name: 'minio-s3'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"