apiVersion: 1

datasources:
  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    name: loki
    type: loki
    uid: loki
    url: http://haproxy:3100
    version: 1
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: ${GRAFANA_DATASOURCE_USER}
    secureJsonData:
      basicAuthPassword: ${GRAFANA_DATASOURCE_PASSWORD}
    isDefault: true
    editable: true