name: Deploy facade

on:
  workflow_run:
    workflows:
      - "Build facade image"
    types:
      - "completed"
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

env:
  JFROG_USERNAME_DEPLOY_ACCESS_TOKEN: ${{ secrets.JFROG_USERNAME_DEPLOY_ACCESS_TOKEN }}
  JFROG_USERNAME_DEPLOY_USERNAME: ${{ secrets.JFROG_USERNAME_DEPLOY_USERNAME }}
  JFROG_URL: exchangetypescript.jfrog.io

  PROJECT_DIR: "exchange_typescript"
  GIT_URL: "https://github.com/epershinaass/exchange_typescript"

  SERVICE_URL: "0.0.0.0"
  FACADE_SERVICE_PORT: 3000
  BALANCE_URL: "balance"
  BALANCE_SERVICE_PORT: 5000
  PRODUCTS_URL: "products"
  PRODUCTS_SERVICE_PORT: 5001
  ACCOUNT_URL: "account"
  ACCOUNT_SERVICE_PORT: 5002

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_DIR,GIT_URL,JFROG_USERNAME_DEPLOY_ACCESS_TOKEN,JFROG_USERNAME_DEPLOY_USERNAME,SERVICE_URL,FACADE_SERVICE_PORT,BALANCE_URL,BALANCE_SERVICE_PORT,PRODUCTS_URL,PRODUCTS_SERVICE_PORT,ACCOUNT_SERVICE_PORT,ACCOUNT_URL,JFROG_URL
          script: |
            if [ -d $PROJECT_DIR ]; then
              cd $PROJECT_DIR && git pull
            else
              git clone $GIT_URL && cd $PROJECT_DIR
            fi

            echo "JFROG_USERNAME_DEPLOY_ACCESS_TOKEN=$JFROG_USERNAME_DEPLOY_ACCESS_TOKEN
            JFROG_USERNAME_DEPLOY_USERNAME=$JFROG_USERNAME_DEPLOY_USERNAME
            JFROG_URL=$JFROG_URL
            FACADE_SERVICE_PORT=$FACADE_SERVICE_PORT
            ACCOUNT_SERVICE_PORT=$ACCOUNT_SERVICE_PORT
            PRODUCTS_SERVICE_PORT=$PRODUCTS_SERVICE_PORT
            BALANCE_SERVICE_PORT=$BALANCE_SERVICE_PORT
            COMPOSE_HTTP_TIMEOUT=500" > fs.env


            echo "
            BALANCE_PORT=$BALANCE_SERVICE_PORT
            BALANCE_URL=$BALANCE_URL
            ACCOUNT_URL=$ACCOUNT_URL
            ACCOUNT_PORT=$ACCOUNT_SERVICE_PORT
            SERVICE_URL=$SERVICE_URL
            SERVICE_PORT=$FACADE_SERVICE_PORT
            PRODUCTS_URL=$PRODUCTS_URL
            PRODUCTS_PORT=$PRODUCTS_SERVICE_PORT" > ./facade/.env

            export $(cat fs.env | egrep -v "(^#.*|^$)" | xargs)
            docker login -u $JFROG_USERNAME_DEPLOY_USERNAME -p $JFROG_USERNAME_DEPLOY_ACCESS_TOKEN $JFROG_URL
            docker-compose --profile facade -f ./infra/docker-compose-app.yaml --env-file fs.env up -d
            rm fs.env
            rm ./facade/.env
            git restore .
            git clean -dxf
            docker logout
