name: Lint Dockerfile
on:
  pull_request:
    types: [opened, reopened]
    paths:
    - 'Dockerfile'
    - 'facade/Dockerfile'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'none'
          filters: |
            root:
              - 'Dockerfile'
            facade:
              - 'facade/Dockerfile'
      - name: Validate root Dockerfile
        if: steps.changes.outputs.root == 'true'
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: 'Dockerfile'
      - name: Validate facade Dockerfile
        if: steps.changes.outputs.facade == 'true'
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: 'facade/Dockerfile'