name: remote deploy to Server 1

on:
  workflow_dispatch:

env:
  # MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
  # MONGO_MONGODB_EXPORTER_PASSWORD: ${{ secrets.MONGO_MONGODB_EXPORTER_PASSWORD }}
  # MONGO_SERVICE_PASSWORD: ${{ secrets.MONGO_SERVICE_PASSWORD }}
  # GRAFANA_DOMAIN: ${{ secrets.SERVER1 }}
  # GRAFANA_DEFAULT_ADMIN_PASSWORD: ${{ secrets.GRAFANA_DEFAULT_ADMIN_PASSWORD }}
  # GRAFANA_DATASOURCE_PASSWORD: ${{ secrets.GRAFANA_DATASOURCE_PASSWORD }}
  # PROMETHEUS_DOMAIN: ${{ secrets.SERVER1 }}
  # ALERTMANAGER_TELEGRAM_BOT_TOKEN: ${{ secrets.ALERTMANAGER_TELEGRAM_BOT_TOKEN }}
  # ALERTMANAGER_TELEGRAM_CHAT_ID: ${{ secrets.ALERTMANAGER_TELEGRAM_CHAT_ID }}
  # PROJECT_DIR: "exchange_typescript"
  # GIT_URL: "https://github.com/epershinaass/exchange_typescript"
  MONGO_INITDB_ROOT_PASSWORD: "passwd"
  MONGO_MONGODB_EXPORTER_PASSWORD: "exp-passwd"
  MONGO_SERVICE_PASSWORD: "mng-passwd"
  GRAFANA_DOMAIN: "0.0.0.0"
  GRAFANA_DEFAULT_ADMIN_PASSWORD: "admin"
  GRAFANA_DATASOURCE_PASSWORD: "admin"
  PROMETHEUS_DOMAIN: "0.0.0.0"
  ALERTMANAGER_TELEGRAM_BOT_TOKEN: "roken"
  ALERTMANAGER_TELEGRAM_CHAT_ID: "id"
  PROJECT_DIR: "exchange_typescript"
  GIT_URL: "https://github.com/epershinaass/exchange_typescript"


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: MONGO_INITDB_ROOT_PASSWORD,MONGO_MONGODB_EXPORTER_PASSWORD,MONGO_SERVICE_PASSWORD,GRAFANA_DOMAIN,GRAFANA_DEFAULT_ADMIN_PASSWORD,GRAFANA_DATASOURCE_PASSWORD,PROMETHEUS_DOMAIN,ALERTMANAGER_TELEGRAM_BOT_TOKEN,ALERTMANAGER_TELEGRAM_CHAT_ID,PROJECT_DIR,GIT_URL
          script: |
            # export MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            # export MONGO_MONGODB_EXPORTER_PASSWORD=${{ secrets.MONGO_MONGODB_EXPORTER_PASSWORD }}
            # export MONGO_SERVICE_PASSWORD=${{ secrets.MONGO_SERVICE_PASSWORD }}
            # export GRAFANA_DOMAIN=${{ secrets.SERVER1 }}
            # export GRAFANA_DEFAULT_ADMIN_PASSWORD=${{ secrets.GRAFANA_DEFAULT_ADMIN_PASSWORD }}
            # export GRAFANA_DATASOURCE_PASSWORD=${{ secrets.GRAFANA_DATASOURCE_PASSWORD }}
            # export PROMETHEUS_DOMAIN=${{ secrets.SERVER1 }}
            # export ALERTMANAGER_TELEGRAM_BOT_TOKEN=${{ secrets.ALERTMANAGER_TELEGRAM_BOT_TOKEN }}
            # export ALERTMANAGER_TELEGRAM_CHAT_ID=${{ secrets.ALERTMANAGER_TELEGRAM_CHAT_ID }}
            # export PROJECT_DIR="exchange_typescript"
            # export GIT_URL=$GIT_URL
            
            echo $MONGO_INITDB_ROOT_PASSWORD
            echo $MONGO_MONGODB_EXPORTER_PASSWORD
            echo $MONGO_SERVICE_PASSWORD
            echo $GRAFANA_DOMAIN
            echo $GRAFANA_DEFAULT_ADMIN_PASSWORD
            echo $PROMETHEUS_DOMAIN
            echo $ALERTMANAGER_TELEGRAM_BOT_TOKEN
            echo $ALERTMANAGER_TELEGRAM_CHAT_ID
            echo "PROJECT_DIR=$PROJECT_DIR"
            echo "GIT_URL=$GIT_URL"
            
            if [ -d $PROJECT_DIR ]; then
              cd $PROJECT_DIR && git pull
            else
              git clone $GIT_URL && cd $PROJECT_DIR
            fi
            docker-compose --profile full -f ./infra/docker-compose.yaml up -d
