name: telegram message on PR
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "closed"
      - "converted_to_draft"
      - "synchronize"
  pull_request_review:
  pull_request_review_comment:
jobs:

  message:
    name: message
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 10
    steps:
      - name: send telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} ${{ github.event.action }} PR #${{ github.event.number }}:
            From ${{ github.head_ref }} to ${{ github.base_ref }}
            Title: ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.body }}
            Reviewers: ${{ github.event.pull_request.requested_reviewers[@] }}
            Last head label: ${{ github.event.pull_request.head.label }}
            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}

  message-review:
    name: message reviews
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_review' }}
    timeout-minutes: 10
    steps:
      - name: send telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event.pull_request_review.review.user }} ${{ github.event.pull_request_review.action }} PR #${{ github.event.pull_request_review.pull_request.number }}
            Pull request title: ${{ github.event.pull_request_review.pull_request.title }}
            See: ${{ github.event.pull_request_review.review.html_url }}

  message-review-comment:
    name: message reviews comment
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_review_comment' }}
    timeout-minutes: 10
    steps:
      - name: send telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event.pull_request_review_comment.comment.user.login }} ${{ github.event.pull_request_review_comment.action }} comment.
            File: ${{ github.event.pull_request_review_comment.comment.path }}

            Text: ${{ github.event.pull_request_review_comment.comment.body }}

            See: ${{ github.event.pull_request_review_comment.comment.html_url }}
            PR#${{ github.event.pull_request_review_comment.pull_request.number }}
            Link: ${{ github.event.pull_request_review_comment.pull_request.html_url }}