name: telegram message
on:
  push:
    branches:
      - "main"

jobs:

  message:
    name: message
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}